image: Visual Studio 2017 RC
version: '0.1.0.{build}'
configuration:
- Release
platform: Any CPU
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  NUGET_API_KEY:
    secure: Lg87f7FMaIazSs+Cmlhk5y7elJBeQ+h/FiI6tC+XJtBKqTxHpCWlTq+nvBPPfH/x
before_build:
- nuget install Cake -ExcludeVersion
build_script:
- .\Cake\Cake.exe --target=Build --packageVersion=%APPVEYOR_BUILD_VERSION% --currentBranch=%APPVEYOR_REPO_BRANCH% --verbosity=Verbose
after_build:
- .\Cake\Cake.exe --target=Pack --packageVersion=%APPVEYOR_BUILD_VERSION% --currentBranch=%APPVEYOR_REPO_BRANCH%
test_script:
- .\Cake\Cake.exe --target=UnitTest
deploy:
  provider: NuGet
  server: https://www.myget.org/F/protoactor/api/v2/package
  api_key:
    secure: Lg87f7FMaIazSs+Cmlhk5y7elJBeQ+h/FiI6tC+XJtBKqTxHpCWlTq+nvBPPfH/x
  skip_symbols: false
  symbol_server: https://www.myget.org/F/protoactor/symbols/api/v2/package
artifacts:
- path: out\*
